include:
  - project: tonplay/gitlabci-templates
    ref: master
    file: /defaults/web3-gaming.yml
  - project: tonplay/gitlabci-templates
    ref: roguelike-ci
    file: /snippets/build.yml
  - project: tonplay/gitlabci-templates
    ref: master
    file: /snippets/deploy.yml

stages:
  - build
  - deploy

.build-hellsweep:
  extends: .build-docker
  stage: build
  variables:
    IMAGE_NAME: hellsweep-asia-front
    SERVICE_PATH: BuildTemplate/webgl
    DIR: ./BuildTemplate/webgl

Build Hellsweep (dev):
  extends:
    - .build-hellsweep
  variables:
    IMAGE_TAG: dev
  rules:
    - !reference [.if-dev-branch, rules]

Build Hellsweep (main):
  extends:
    - .build-hellsweep
  rules:
    - !reference [.if-main-branch, rules]

Deploy Hellsweep:
  extends:
    - .deploy-image-cloudrun-manual-dev
  stage: deploy
  variables:
    APP_NAME: hellsweep-front-dev-asia
    IMAGE_NAME: hellsweep-asia-front-dev
    SERVICE_PATH: BuildTemplate/webgl
