include:
- project: tonplay/gitlabci-templates
  ref: master
  file: /defaults/web3-gaming.yml
- project: tonplay/gitlabci-templates
  ref: master
  file: /snippets/build.yml
- project: tonplay/gitlabci-templates
  ref: master
  file: /snippets/deploy.yml


stages:
- build


Build Hellsweep:
  extends: .build-docker-manual
  stage: build
  variables:
    IMAGE_NAME: hellsweep-asia-front-dev
    IMAGE_TAG: dev
    SERVICE_PATH: BuildTemplate/webgl
    DIR: ./BuildTemplate/webgl


Deploy Hellsweep:
  extends: .deploy-image-cloudrun-manual-dev
  stage: deploy
  variables:
    APP_NAME: hellsweep-front-dev-asia
    IMAGE_NAME: hellsweep-asia-front-dev
    SERVICE_PATH: BuildTemplate/webgl

